import streamlit as st
from fpdf import FPDF
from datetime import datetime
import calendar

# 1. The PDF Engine Class
class PaySlipPDF(FPDF):
    def header(self):
        # Professional Header for Al-Ibrahim Medicare
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'PAYSLIP', 0, 1, 'C')
        self.set_font('Arial', 'B', 12)
        self.cell(0, 7, 'AL-IBRAHIM MEDICARE', 0, 1, 'C')
        self.set_font('Arial', '', 9)
        self.cell(0, 5, '40H BLOCK COMMERCIAL MARKET, FAISALABAD', 0, 1, 'C')
        self.cell(0, 5, 'CONTACT: 03017544420 / 03352276200', 0, 1, 'C')
        self.ln(10)

# 2. The Web Application Layout
st.set_page_config(page_title="Al-Ibrahim Medicare Portal", page_icon="🏥")

st.title("🏥 Al-Ibrahim Medicare")
st.subheader("Interactive Pay Slip Generator")

# Automatically detect current month and days
now = datetime.now()
_, total_days = calendar.monthrange(now.year, now.month)
current_month_str = now.strftime('%B %Y')

st.info(f"System Date: **{now.strftime('%Y/%m/%d')}** | Days in {now.strftime('%B')}: **{total_days}**")

# Input Form
with st.form("payslip_form"):
    col1, col2 = st.columns(2)
    with col1:
        emp_name = st.text_input("Employee Name")
        basic_pay = st.number_input("Monthly Basic Salary", min_value=0.0, step=100.0, value=40000.0)
    with col2:
        absent_days = st.number_input("Days Absent", min_value=0, max_value=total_days, value=0)
        allowance = st.number_input("Allowances/Shares", min_value=0.0, step=100.0, value=0.0)
        tax = st.number_input("Tax Deduction", min_value=0.0, step=10.0, value=0.0)
    
    submit = st.form_submit_button("Generate Pay Slip")

if submit:
    if not emp_name:
        st.warning("Please enter an employee name to proceed.")
    else:
        # Calculations
        daily_rate = basic_pay / total_days
        non_work_deduction = daily_rate * absent_days
        total_earnings = basic_pay + allowance
        total_deductions = tax + non_work_deduction
        net_pay = total_earnings - total_deductions
        
        # Build the PDF
        pdf = PaySlipPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=10)
        
        # Top Details
        pdf.cell(95, 8, f"Pay Date: {now.strftime('%Y/%m/%d')}", 0)
        pdf.cell(95, 8, f"Employee Name: {emp_name}", 0, 1)
        pdf.cell(95, 8, f"Month: {current_month_str}", 0)
        pdf.cell(95, 8, f"Days Worked: {total_days - absent_days}", 0, 1)
        pdf.ln(10)
        
        # --- Centered Table Logic ---
        table_width = 100 
        start_x = (210 - table_width) / 2  # 55mm for center alignment
        
        # Table Header
        pdf.set_x(start_x)
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font("Arial", 'B', 10)
        pdf.cell(60, 10, "Description", 1, 0, 'L', 1)
        pdf.cell(40, 10, "Amount", 1, 1, 'R', 1)
        
        # Table Content
        pdf.set_font("Arial", '', 10)
        
        pdf.set_x(start_x)
        pdf.cell(60, 10, "Basic Salary", 1)
        pdf.cell(40, 10, f"{basic_pay:.2f}", 1, 1, 'R')
        
        pdf.set_x(start_x)
        pdf.cell(60, 10, "Allowances/Shares", 1)
        pdf.cell(40, 10, f"{allowance:.2f}", 1, 1, 'R')
        
        pdf.set_x(start_x)
        pdf.cell(60, 10, f"Absent ({absent_days} days)", 1)
        pdf.cell(40, 10, f"-{non_work_deduction:.2f}", 1, 1, 'R')
        
        pdf.set_x(start_x)
        pdf.cell(60, 10, "Income Tax", 1)
        pdf.cell(40, 10, f"-{tax:.2f}", 1, 1, 'R')
        
        # Net Payable Highlight
        pdf.set_x(start_x)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(60, 12, "NET PAYABLE", 1)
        pdf.cell(40, 12, f"{net_pay:.2f}", 1, 1, 'R')
        
        # Signatures
        pdf.ln(20)
        pdf.set_font("Arial", '', 10)
        pdf.cell(90, 10, "__________________________", 0, 0, 'C')
        pdf.cell(90, 10, "__________________________", 0, 1, 'C')
        pdf.cell(90, 5, "Employer Signature", 0, 0, 'C')
        pdf.cell(90, 5, "Employee Signature", 0, 1, 'C')
        
        # System Message
        pdf.ln(10)
        pdf.set_font("Arial", 'I', 8)
        pdf.cell(0, 10, "Generated by Al-Ibrahim Medicare Automated System", 0, 1, 'C')

        # Generate output for download
        pdf_bytes = pdf.output() 
        
        st.success(f"Success! Pay slip for {emp_name} generated.")
        st.download_button(
            label="⬇️ Download Pay Slip PDF",
            data=bytes(pdf_bytes),
            file_name=f"Payslip_{emp_name.replace(' ', '_')}_{now.strftime('%b_%Y')}.pdf",
            mime="application/pdf"
        )
