import streamlit as st
from fpdf import FPDF
from datetime import datetime
import calendar
import os

# 1. The PDF Engine Class
class PaySlipPDF(FPDF):
    def header(self):
        logo_path = "logo.png"
        if os.path.exists(logo_path):
            self.image(logo_path, x=85, y=10, w=40)
            self.set_y(55) 
        else:
            self.set_y(10)

        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'PAYSLIP', 0, 1, 'C')
        self.set_font('Arial', 'B', 12)
        self.cell(0, 7, 'AL-IBRAHIM MEDICARE', 0, 1, 'C')
        self.set_font('Arial', '', 9)
        self.cell(0, 5, '40H BLOCK COMMERCIAL MARKET, FAISALABAD', 0, 1, 'C')
        self.cell(0, 5, 'CONTACT: 03017544420 / 03352276200', 0, 1, 'C')
        self.ln(10)

# 2. The Web Application Layout
st.set_page_config(page_title="Al-Ibrahim Medicare Portal", page_icon="🏥")

st.title("🏥 Al-Ibrahim Medicare")
st.subheader("Interactive Pay Slip Generator")

now = datetime.now()
_, total_days = calendar.monthrange(now.year, now.month)
current_month_str = now.strftime('%B %Y')

st.info(f"System Date: **{now.strftime('%Y/%m/%d')}** | Days in {now.strftime('%B')}: **{total_days}**")

with st.form("payslip_form"):
    col1, col2 = st.columns(2)
    with col1:
        emp_name = st.text_input("Employee Name")
        basic_pay = st.number_input("Monthly Basic Salary", min_value=0.0, step=100.0, value=40000.0)
    with col2:
        absent_days = st.number_input("Days Absent", min_value=0, max_value=total_days, value=0)
        allowance = st.number_input("Allowances/Shares", min_value=0.0, step=100.0, value=0.0)
        tax = st.number_input("Tax Deduction", min_value=0.0, step=10.0, value=0.0)
    
    submit = st.form_submit_button("Generate Pay Slip")

if submit:
    if not emp_name:
        st.warning("Please enter an employee name to proceed.")
    else:
        daily_rate = basic_pay / total_days
        non_work_deduction = daily_rate * absent_days
        total_earnings = basic_pay + allowance
        total_deductions = tax + non_work_deduction
        net_pay = total_earnings - total_deductions
        
        pdf = PaySlipPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=10)
        
        # --- Adjusted Centered Employee Info Section ---
        start_x = 55
        
        # Row 1
        pdf.set_x(start_x)
        pdf.cell(50, 10, f"Pay Date: {now.strftime('%Y/%m/%d')}", 0)
        pdf.cell(50, 10, f"Employee Name: {emp_name}", 0, 1)
        
        # Extra nudge for space
        pdf.ln(2) 
        
        # Row 2
        pdf.set_x(start_x)
        pdf.cell(50, 10, f"Month: {current_month_str}", 0)
        pdf.cell(50, 10, f"Days Worked: {total_days - absent_days}", 0, 1)
        
        pdf.ln(10) # More space before the table
        
        # --- Centered Table Section ---
        pdf.set_x(start_x)
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font("Arial", 'B', 10)
        pdf.cell(60, 10, "Description", 1, 0, 'L', 1)
        pdf.cell(40, 10, "Amount", 1, 1, 'R', 1)
        
        pdf.set_font("Arial", '', 10)
        rows = [
            ("Basic Salary", basic_pay),
            ("Allowances/Shares", allowance),
            (f"Absent ({absent_days} days)", -non_work_deduction),
            ("Income Tax", -tax)
        ]
        
        for desc, amt in rows:
            pdf.set_x(start_x)
            pdf.cell(60, 10, desc, 1)
            pdf.cell(40, 10, f"{amt:.2f}", 1, 1, 'R')
        
        pdf.set_x(start_x)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(60, 12, "NET PAYABLE", 1)
        pdf.cell(40, 12, f"{net_pay:.2f}", 1, 1, 'R')
        
        pdf.ln(20)
        pdf.set_font("Arial", '', 10)
        pdf.cell(90, 10, "__________________________", 0, 0, 'C')
        pdf.cell(90, 10, "__________________________", 0, 1, 'C')
        pdf.cell(90, 5, "Employer Signature", 0, 0, 'C')
        pdf.cell(90, 5, "Employee Signature", 0, 1, 'C')
        
        pdf.ln(10)
        pdf.set_font("Arial", 'I', 8)
        pdf.cell(0, 10, "Generated by Al-Ibrahim Medicare Automated System", 0, 1, 'C')

        pdf_bytes = pdf.output() 
        
        st.success(f"Success! Pay slip for {emp_name} generated.")
        st.download_button(
            label="⬇️ Download Pay Slip PDF",
            data=bytes(pdf_bytes),
            file_name=f"Payslip_{emp_name.replace(' ', '_')}_{now.strftime('%b_%Y')}.pdf",
            mime="application/pdf"
        )
